site_name: NeuroGeriatricsMotionToolbox

extra_css:
  - 'style.css'

plugins:
- search
- mkdocs-jupyter
- mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [ngmt]

theme:
  name: material
  logo: ngmt_logo_transBG.png
  language: en
  font:
    text: "Roboto"
    code: "Roboto Mono"
  palette:
    - scheme: default
      primary: light green
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple  # primary color for dark mode
      accent: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        
  features:
    - navigation.tabs

nav:
  - Home: index.md
  - Examples: 
    - examples/index.md
    - Tutorial basics: examples/basic_00_intro_ngmt.md
    - Load data into NGMT: examples/basic_01_load_Data.md
    - Events in dataclass: examples/basic_02_events.md
    - Gait Sequence Detection: examples/modules_01_gsd.md
    - Initial Contact Detection: examples/modules_02_icd.md
    - Physical Activity Monitoring: examples/03_tutorial_physical_activity_monitoring.md
    - Sit to Stand and Stand to Sit Detection: examples/05_tutorial_sit_to_stand_stand_to_sit_detection.md
  - Modules: 
    - modules/index.md
    - Gait Sequence Detection: modules/gsd.md
    - Initial Contact Detection: modules/icd.md
    - Physical Activity Monitoring: modules/pam.md
    - Sit to Stand and Stand to Sit Detection: modules/ssd.md
  - Dataclass: dataclass.md
  - Datasets:
    - datasets/index.md
    - KeepControl: datasets/keepcontrol.md
    - Mobilise-D: datasets/mobilised.md
  - Utilities: 
    - utils/index.md
    - Data Preprocessing: utils/preprocessing.md
    - Data Import: utils/importers.md
    - Orientation Estimation: utils/orientation_estimation.md
  - Contributing: 
    - contributing.md

markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format

